from django.urls import path
from . import views

urlpatterns = [
    path('admin/main', views.admin_main, name='admin-main'),
    path('logout/', views.admin_logout, name='admin-logout'),
    path('admin/post/<int:post_id>/', views.admin_post_detail, name='admin-post-detail'),
    path('admin/like/<int:post_id>/', views.admin_like_post, name='admin-like-post'),
    path('admin/like-comment/<int:comment_id>/', views.like_comment, name='like_comment'),
    path('admin/panel/', views.admin_panel, name='admin-panel'),
    path('admin/panel/user-management/', views.user_management, name='user-management'),
    path('admin/panel/user-management/edit/<int:user_id>/', views.edit_user, name='edit-user'),
    path('admin/panel/user-management/delete/<int:user_id>/', views.delete_user_confirmation, name='delete-user-confirmation'),
    path('admin/panel/user-management/delete/execute/<int:user_id>/', views.user_delete, name='delete-user-execute'),
    path('admin/panel/user-management/adduser/', views.add_user, name='add-user'),
    path('admin/profile/<int:user_id>', views.view_profile, name='view-profile'),
    path('admin/profile/my', views.admin_profile, name='my-profile'),
    path('admin/panel/user-management/delete/batch-confirm/', views.batch_delete_confirmation, name='batch-delete-confirmation'),
    path('admin/panel/user-management/delete/batch-execute/', views.batch_delete_execute, name='batch-delete-execute'),
    path('admin/panel/feedback/home/', views.feedback_center, name="feedback-center"),
    path('admin/panel/feedback/detail/<int:feedback_id>', views.feedback_detail, name="admin-feedback-detail"),
    path('admin/panel/report/home/', views.report_center, name='report-center'),
    path('admin/panel/report/process/<str:report_type>/<int:report_id>/', views.report_process, name='report-process'),
    path('admin/notifications/', views.admin_notifications, name='admin-notifications'),
    path('admin/main/<str:major_name>/', views.admin_major, name='admin-major'),
    path('admin/panel/database/', views.admin_database_management, name='database-management'),
    path('admin/panel/database/major/add/', views.database_add, {'model_type': 'major'}, name='add-major'),
    path('admin/panel/database/major/edit/<int:item_id>/', views.database_edit, {'model_type': 'major'}, name='edit-major'),
    path('admin/panel/database/category/add/', views.database_add, {'model_type': 'category'}, name='add-category'),
    path('admin/panel/database/category/edit/<int:item_id>/', views.database_edit, {'model_type': 'category'}, name='edit-category'),
    path('admin/panel/database/major/delete-confirm/<int:item_id>/', views.database_delete_confirmation, {'model_type': 'major'}, name='delete-major-confirmation'),
    path('admin/panel/database/category/delete-confirm/<int:item_id>/', views.database_delete_confirmation, {'model_type': 'category'}, name='delete-category-confirmation'),
    path('admin/panel/database/major/delete/<int:item_id>/', views.database_delete_execute, {'model_type': 'major'}, name='delete-major-execute'),
    path('admin/panel/database/category/delete/<int:item_id>/', views.database_delete_execute, {'model_type': 'category'}, name='delete-category-execute'),
    path('admin/post/edit/<int:post_id>/', views.admin_edit_post, name='admin-edit-post'),
    path('admin/post/delete/<int:post_id>/', views.admin_delete_post, name='admin-delete-post'),
    path('admin/create-post/', views.admin_create_post, name='admin-create-post'),
    path('admin/comment/delete/<int:comment_id>', views.admin_delete_comment, name='admin-delete-comment'),
    path('admin/panel/offenders/', views.offender, name='offender-management'),
    path('admin/add-comment/<int:post_id>/', views.admin_add_comment, name='admin-add-comment'),
]