# Generated by Django 6.0.3 on 2026-05-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/default.png', null=True, upload_to='profile_picture/'),
        ),
    ]
