# Generated by Django 6.0.3 on 2026-05-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_like', 'liked your post'), ('post_comment', 'commented on your post'), ('comment_reply', 'replied to your comment'), ('comment_like', 'liked your comment'), ('admin_reply', 'replied to your feedback'), ('feedback_submitted', 'You have submitted a feedback.')], max_length=20),
        ),
    ]
