# Generated by Django 6.0.3 on 2026-06-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_like', 'liked your post'), ('post_comment', 'commented on your post'), ('comment_reply', 'replied to your comment'), ('comment_like', 'liked your comment'), ('admin_reply', 'replied to your feedback'), ('feedback_submitted', 'You have submitted a feedback.'), ('report_approved', 'Report Approved'), ('report_dismissed', 'Report Dismissed'), ('content_warning', 'Content Warning'), ('content_deleted', 'Content Deleted'), ('account_suspended', 'Account Suspended')], max_length=20),
        ),
    ]
