# Generated by Django 6.0.3 on 2026-06-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_like', 'liked your post'), ('post_comment', 'commented on your post'), ('comment_reply', 'replied to your comment'), ('comment_like', 'liked your comment'), ('admin_reply', 'replied to your feedback'), ('feedback_submitted', 'You have submitted a feedback.'), ('report_approved', 'Report Approved'), ('report_dismissed', 'Report Dismissed'), ('content_warning', 'Content Warning'), ('content_deleted', 'Content Deleted'), ('account_suspended', 'Account Suspended'), ('new_feedback', 'submitted a new feedback'), ('new_report', 'submitted a new report')], max_length=20),
        ),
    ]
