# Generated by Django 6.0.3 on 2026-06-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profileotp'),
        ('user', '0009_notification_content_type_notification_object_id_and_more'),
    ]

    operations = [
    ]
