# Generated by Django 6.0.3 on 2026-06-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_offender'),
    ]

    operations = [
        migrations.AddField(
            model_name='offender',
            name='resolution',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
