# Generated by Django 6.0.3 on 2026-07-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_offender_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='major_shortform',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
