# Generated by Django 6.0.3 on 2026-07-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_major_major_shortform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='major_shortform',
        ),
    ]
