# Generated by Django 6.0.3 on 2026-07-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_major_major_shortform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user/static/user/images/default.png', null=True, upload_to='profile_picture/'),
        ),
    ]
