# Generated by Django 6.0.3 on 2026-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/default.png', null=True, upload_to='profile_picture/'),
        ),
    ]
