# Generated by Django 6.0.3 on 2026-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='post_pdfs/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
    ]
