# Generated by Django 6.0.3 on 2026-05-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_pdf_post_video_file'),
        ('post', '0004_alter_comment_post'),
    ]

    operations = [
    ]
