# Generated by Django 6.0.3 on 2026-05-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_merge_20260506_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Post_status',
        ),
    ]
