# Generated by Django 6.0.3 on 2026-05-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment_parent_comment_remove_comment_dislikes_count_and_more'),
        ('post', '0007_report'),
    ]

    operations = [
    ]
