# Generated by Django 6.0.3 on 2026-05-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_is_deleted_post_is_reported_alter_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
