<<<<<<< HEAD
=======
<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-05-14 00:20
=======
# Generated by Django 6.0.4 on 2026-05-12 05:32
>>>>>>> f3ad98c8bb08985431a82578245df330f814f182
>>>>>>> 87e97859a573e405b3c125203ca759a267a18bf0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_is_deleted_post_is_reported_alter_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
