# Generated by Django 6.0.3 on 2026-05-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_report_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
