# Generated by Django 6.0.3 on 2026-06-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_comment_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
    ]
