# Generated by Django 6.0.3 on 2026-06-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_comment_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomment',
            name='resolution',
            field=models.CharField(blank=True, choices=[('approved_deleted', 'Approved - Comment Deleted'), ('aproved_warned', 'Approved - User Warned'), ('approved_suspended', 'Approved - User Suspended'), ('dismissed', 'Dismissed - No Action')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='resolution',
            field=models.CharField(blank=True, choices=[('approved_deleted', 'Approved - Content Deleted'), ('aproved_warned', 'Approved - User Warned'), ('approved_suspended', 'Approved - User Suspended'), ('dismissed', 'Dismissed - No Action')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
