# Generated by Django 6.0.3 on 2026-06-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_reportcomment_resolution_reportcomment_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomment',
            name='resolution',
            field=models.CharField(blank=True, choices=[('approved_deleted', 'Approved - Comment Deleted'), ('approved_warned', 'Approved - User Warned'), ('approved_suspended', 'Approved - User Suspended'), ('dismissed', 'Dismissed - No Action')], max_length=50, null=True),
        ),
    ]
