# Generated by Django 6.0.3 on 2026-06-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_reportcomment_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_announcement',
            field=models.BooleanField(default=False),
        ),
    ]
