# Generated by Django 6.0.3 on 2026-07-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_comment_deleted_at_comment_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
